### ISSUE TITLE
that is good idea why stop now ?

### ISSUE THREAD

**Issue by pythonwood** [mk-fg/graphite-metrics#4]
send sysstat data to graphite carbon server like this.
that is good idea why stop now ?

**Comment by mk-fg** [comment]
Haven't used or really needed the thing for years, as I didn't work with physical machines under any load for a while.
And with various cloud deployments don't think you generally care much about monitoring specific VMs, so don't expect to need it much in the future either.

Also, iirc wrt sysstat, this thing doesn't do much beyond a rather trivial value names translation - just copy that into some python3 script to run in a loop and there you have a decent modern version of the thing :)
